# -*- coding: utf-8 -*-
"""Risk_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nMFWYXj9UC3PadupoABz3BCcL6LVfoxQ

Finding the **Volitility** of return of **Micorsoft Stock**
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_excel("Microsoft Stock.xlsx")
print(df)

df = df.drop(0)

df

mean_return = df['Return'].mean()
print(f"The mean of the 'Return' column is: {mean_return:.3f}")

# Adding a new column 'squared dev' with the calculated value
df['squared dev'] = (df['Return'] - mean_return)**2

print(df.head())

sum_of_squared_deviations = df['squared dev'].sum()
print(f"Sum of squared deviations is {sum_of_squared_deviations:.3f}")

n = len(df)
variance = sum_of_squared_deviations / n
std_dev = variance**0.5
ann_volatility = std_dev * (n**0.5)
print(f"Variance is {variance:.3f}")
print(f"Standard deviation is {std_dev:.3f}")
print(f"Annualized Volatility is {ann_volatility:.3f}")